use crate::ast::{AssignOp, BinaryOp, UnaryOp};
use crate::sema::{
    type_size, FunctionId, GlobalInfo, LValue, LocalId, LocalInfo, StructInfo, SwitchLabel, Type,
    TypedBlock, TypedExpr, TypedExprKind, TypedForInit, TypedFunction, TypedInitializer,
    TypedProgram, TypedStmt,
};
use crate::span::{Diagnostic, Span};

const ALLOCATABLE_REGS: usize = 13; // r13/r14 are ABI scratch; r15 is assembler scratch.
const LANE_REG: u8 = 13;
const STACK_ADDR_REG: u8 = 14;
const STACK_POINTER: &str = "s7";
const STACK_TOP: u32 = 16_384;
const SIGN_BIT: u32 = 0x8000_0000;

pub fn generate(program: &TypedProgram) -> Result<String, Diagnostic> {
    Generator::new(program).program(program)
}

#[derive(Clone, Copy)]
struct Value {
    reg: u8,
    owned: bool,
}

struct Generator<'a> {
    assembly: String,
    used: [bool; ALLOCATABLE_REGS],
    local_regs: Vec<Option<u8>>,
    next_label: usize,
    controls: Vec<ControlTarget>,
    switch_labels: Vec<Vec<(usize, String)>>,
    function_labels: Vec<String>,
    current_function: Option<FunctionId>,
    current_return_type: Type,
    current_frame_words: usize,
    main_function: FunctionId,
    locals: &'a [LocalInfo],
    globals: &'a [GlobalInfo],
    structs: &'a [StructInfo],
}

struct ControlTarget {
    break_label: String,
    continue_label: Option<String>,
}

impl<'a> Generator<'a> {
    fn new(program: &'a TypedProgram) -> Self {
        Self {
            assembly: String::new(),
            used: [false; ALLOCATABLE_REGS],
            local_regs: vec![None; program.locals.len()],
            next_label: 0,
            controls: Vec::new(),
            switch_labels: Vec::new(),
            function_labels: program
                .function_names
                .iter()
                .map(|name| format!("__warpc_fn_{name}"))
                .collect(),
            current_function: None,
            current_return_type: Type::VOID,
            current_frame_words: 0,
            main_function: program.main,
            locals: &program.locals,
            globals: &program.globals,
            structs: &program.structs,
        }
    }

    fn program(mut self, program: &TypedProgram) -> Result<String, Diagnostic> {
        self.line("; generated by warpc — Warp C v0.1.4");
        self.line(".scratch r15");
        self.line("entry:");
        self.instr(&format!("LANEID r{LANE_REG}"));
        self.instr(&format!("S_MOV_I {STACK_POINTER}, {STACK_TOP}"));
        if program.data_words.iter().any(|word| *word != 0) {
            self.instr(&format!("CMP_EQ p0, r{LANE_REG}, 0"));
            for (address, word) in program.data_words.iter().copied().enumerate() {
                if word == 0 {
                    continue;
                }
                self.instr(&format!("MOV r0, {address}"));
                self.instr(&format!("MOV r1, {word}"));
                self.instr("@p0 STORE r0, r1");
            }
        }
        self.instr(&format!("JMP {}", self.function_labels[program.main]));
        for function in &program.functions {
            self.function(function)?;
        }
        Ok(self.assembly)
    }

    fn function(&mut self, function: &TypedFunction) -> Result<(), Diagnostic> {
        self.used.fill(false);
        self.local_regs.fill(None);
        self.controls.clear();
        self.switch_labels.clear();
        self.current_function = Some(function.id);
        self.current_return_type = function.return_type;
        self.current_frame_words = function.frame_words;
        self.line(&format!("{}:", self.function_labels[function.id]));
        for reg in 0..function.params.len() {
            self.used[reg] = true;
        }
        if function.frame_words != 0 {
            self.instr(&format!(
                "S_ADD_I {STACK_POINTER}, {STACK_POINTER}, -{}",
                function.frame_words * 32
            ));
        }
        for (reg, &local) in function.params.iter().enumerate() {
            if self.locals[local].frame_offset.is_some() {
                let address = self.local_address(local, function.span)?;
                self.instr(&format!("STORE r{}, r{reg}", address.reg));
                self.release(address);
                self.used[reg] = false;
            } else {
                self.local_regs[local] = Some(reg as u8);
            }
        }
        self.block(&function.body)?;
        if function.id == self.main_function {
            self.instr("MOV r0, 0");
            self.emit_return();
        } else {
            if function.return_type != Type::VOID {
                self.instr("MOV r0, 0");
            }
            self.emit_return();
        }
        for &local in function.params.iter().rev() {
            if let Some(reg) = self.local_regs[local].take() {
                self.free_reg(reg);
            }
        }
        self.current_function = None;
        Ok(())
    }

    fn block(&mut self, block: &TypedBlock) -> Result<(), Diagnostic> {
        for statement in &block.statements {
            self.statement(statement)?;
        }
        for &local in block.local_ids.iter().rev() {
            if let Some(reg) = self.local_regs[local].take() {
                self.free_reg(reg);
            }
        }
        Ok(())
    }

    fn statement(&mut self, statement: &TypedStmt) -> Result<(), Diagnostic> {
        match statement {
            TypedStmt::Decl { local, init, span } => {
                self.declaration(*local, init.as_ref(), *span)?;
            }
            TypedStmt::Expr(value) => {
                if let Some(value) = value {
                    let result = self.expr(value)?;
                    self.release(result);
                }
            }
            TypedStmt::Return(value, span) => {
                if let Some(value) = value {
                    let result = self.expr(value)?;
                    if result.reg != 0 {
                        self.instr(&format!("MOV r0, r{}", result.reg));
                    }
                    self.release(result);
                } else if self.current_return_type != Type::VOID {
                    return Err(Diagnostic::new(
                        *span,
                        "internal error: non-void return has no value",
                    ));
                }
                self.emit_return();
            }
            TypedStmt::Block(block) => self.block(block)?,
            TypedStmt::If {
                condition,
                then_branch,
                else_branch,
                ..
            } => self.if_statement(condition, then_branch, else_branch.as_deref())?,
            TypedStmt::While {
                condition, body, ..
            } => self.while_statement(condition, body)?,
            TypedStmt::DoWhile {
                body, condition, ..
            } => self.do_while_statement(body, condition)?,
            TypedStmt::For {
                init,
                condition,
                step,
                body,
                local_ids,
                ..
            } => self.for_statement(
                init.as_deref(),
                condition.as_deref(),
                step.as_deref(),
                body,
                local_ids,
            )?,
            TypedStmt::Break(span) => {
                let Some(target) = self.controls.last() else {
                    return Err(Diagnostic::new(
                        *span,
                        "internal error: break target missing",
                    ));
                };
                self.instr(&format!("JMP {}", target.break_label));
            }
            TypedStmt::Continue(span) => {
                let Some(label) = self
                    .controls
                    .iter()
                    .rev()
                    .find_map(|target| target.continue_label.clone())
                else {
                    return Err(Diagnostic::new(
                        *span,
                        "internal error: continue target missing",
                    ));
                };
                self.instr(&format!("JMP {label}"));
            }
            TypedStmt::Switch {
                expression,
                body,
                labels,
                ..
            } => self.switch_statement(expression, body, labels)?,
            TypedStmt::Case { id, body, span } | TypedStmt::Default { id, body, span } => {
                let Some(label) = self.switch_label(*id) else {
                    return Err(Diagnostic::new(
                        *span,
                        "internal error: switch label missing",
                    ));
                };
                self.line(&format!("{label}:"));
                self.statement(body)?;
            }
        }
        Ok(())
    }

    fn if_statement(
        &mut self,
        condition: &TypedExpr,
        then_branch: &TypedStmt,
        else_branch: Option<&TypedStmt>,
    ) -> Result<(), Diagnostic> {
        let otherwise = self.label("if_else");
        let end = self.label("if_end");
        self.jump_if_zero(condition, &otherwise)?;
        self.statement(then_branch)?;
        if let Some(else_branch) = else_branch {
            self.instr(&format!("JMP {end}"));
            self.line(&format!("{otherwise}:"));
            self.statement(else_branch)?;
            self.line(&format!("{end}:"));
        } else {
            self.line(&format!("{otherwise}:"));
        }
        Ok(())
    }

    fn while_statement(
        &mut self,
        condition: &TypedExpr,
        body: &TypedStmt,
    ) -> Result<(), Diagnostic> {
        let condition_label = self.label("while_condition");
        let end = self.label("while_end");
        self.line(&format!("{condition_label}:"));
        self.jump_if_zero(condition, &end)?;
        self.controls.push(ControlTarget {
            break_label: end.clone(),
            continue_label: Some(condition_label.clone()),
        });
        self.statement(body)?;
        self.controls.pop();
        self.instr(&format!("JMP {condition_label}"));
        self.line(&format!("{end}:"));
        Ok(())
    }

    fn do_while_statement(
        &mut self,
        body: &TypedStmt,
        condition: &TypedExpr,
    ) -> Result<(), Diagnostic> {
        let body_label = self.label("do_body");
        let condition_label = self.label("do_condition");
        let end = self.label("do_end");
        self.line(&format!("{body_label}:"));
        self.controls.push(ControlTarget {
            break_label: end.clone(),
            continue_label: Some(condition_label.clone()),
        });
        self.statement(body)?;
        self.controls.pop();
        self.line(&format!("{condition_label}:"));
        self.jump_if_nonzero(condition, &body_label)?;
        self.line(&format!("{end}:"));
        Ok(())
    }

    fn for_statement(
        &mut self,
        init: Option<&TypedForInit>,
        condition: Option<&TypedExpr>,
        step: Option<&TypedExpr>,
        body: &TypedStmt,
        local_ids: &[LocalId],
    ) -> Result<(), Diagnostic> {
        if let Some(init) = init {
            match init {
                TypedForInit::Decl { local, init, span } => {
                    self.declaration(*local, init.as_ref(), *span)?;
                }
                TypedForInit::Expr(expr) => {
                    let value = self.expr(expr)?;
                    self.release(value);
                }
            }
        }
        let condition_label = self.label("for_condition");
        let step_label = self.label("for_step");
        let end = self.label("for_end");
        self.line(&format!("{condition_label}:"));
        if let Some(condition) = condition {
            self.jump_if_zero(condition, &end)?;
        }
        self.controls.push(ControlTarget {
            break_label: end.clone(),
            continue_label: Some(step_label.clone()),
        });
        self.statement(body)?;
        self.controls.pop();
        self.line(&format!("{step_label}:"));
        if let Some(step) = step {
            let value = self.expr(step)?;
            self.release(value);
        }
        self.instr(&format!("JMP {condition_label}"));
        self.line(&format!("{end}:"));
        for &local in local_ids.iter().rev() {
            if let Some(reg) = self.local_regs[local].take() {
                self.free_reg(reg);
            }
        }
        Ok(())
    }

    fn switch_statement(
        &mut self,
        expression: &TypedExpr,
        body: &TypedStmt,
        labels: &[SwitchLabel],
    ) -> Result<(), Diagnostic> {
        let end = self.label("switch_end");
        let mapped: Vec<(usize, String)> = labels
            .iter()
            .map(|label| (label.id, self.label("switch_case")))
            .collect();
        let value = self.expr(expression)?;
        for label in labels.iter().filter(|label| label.value.is_some()) {
            let target = mapped
                .iter()
                .find(|(id, _)| *id == label.id)
                .unwrap()
                .1
                .clone();
            self.instr(&format!(
                "CMP_EQ p0, r{}, {}",
                value.reg,
                label.value.unwrap()
            ));
            self.instr(&format!("JMP_IF_ANY p0, {target}"));
        }
        let default = labels.iter().find(|label| label.value.is_none());
        if let Some(default) = default {
            let target = mapped
                .iter()
                .find(|(id, _)| *id == default.id)
                .unwrap()
                .1
                .clone();
            self.instr(&format!("JMP {target}"));
        } else {
            self.instr(&format!("JMP {end}"));
        }
        self.release(value);

        self.controls.push(ControlTarget {
            break_label: end.clone(),
            continue_label: None,
        });
        self.switch_labels.push(mapped);
        self.statement(body)?;
        self.switch_labels.pop();
        self.controls.pop();
        self.line(&format!("{end}:"));
        Ok(())
    }

    fn declaration(
        &mut self,
        local: LocalId,
        init: Option<&TypedInitializer>,
        span: Span,
    ) -> Result<(), Diagnostic> {
        if self.locals[local].frame_offset.is_some() {
            let size = type_size(self.locals[local].ty, self.structs);
            match init {
                Some(TypedInitializer::Expr(init)) => {
                    let value = self.expr(init)?;
                    let address = self.local_address(local, span)?;
                    self.instr(&format!("STORE r{}, r{}", address.reg, value.reg));
                    self.release(address);
                    self.release(value);
                }
                Some(TypedInitializer::Words(words)) => {
                    for index in 0..size {
                        let address = self.local_address_offset(local, index, span)?;
                        let value = self.alloc_reg(span)?;
                        let word = words.get(index).copied().unwrap_or(0);
                        self.instr(&format!("MOV r{value}, {word}"));
                        self.instr(&format!("STORE r{}, r{value}", address.reg));
                        self.free_reg(value);
                        self.release(address);
                    }
                }
                None => {
                    let zero = self.alloc_reg(span)?;
                    self.instr(&format!("MOV r{zero}, 0"));
                    for index in 0..size {
                        let address = self.local_address_offset(local, index, span)?;
                        self.instr(&format!("STORE r{}, r{zero}", address.reg));
                        self.release(address);
                    }
                    self.free_reg(zero);
                }
            }
            return Ok(());
        }

        let reg = self.alloc_reg(span)?;
        self.local_regs[local] = Some(reg);
        if let Some(TypedInitializer::Expr(init)) = init {
            let value = self.expr(init)?;
            if value.reg != reg {
                self.instr(&format!("MOV r{reg}, r{}", value.reg));
            }
            self.release(value);
        } else if matches!(init, Some(TypedInitializer::Words(_))) {
            return Err(Diagnostic::new(
                span,
                "internal error: aggregate initializer assigned to register local",
            ));
        } else {
            self.instr(&format!("MOV r{reg}, 0"));
        }
        Ok(())
    }

    fn jump_if_zero(&mut self, condition: &TypedExpr, label: &str) -> Result<(), Diagnostic> {
        let value = self.expr(condition)?;
        self.instr(&format!("CMP_EQ p0, r{}, 0", value.reg));
        self.release(value);
        self.instr(&format!("JMP_IF_ANY p0, {label}"));
        Ok(())
    }

    fn jump_if_nonzero(&mut self, condition: &TypedExpr, label: &str) -> Result<(), Diagnostic> {
        let value = self.expr(condition)?;
        self.instr(&format!("CMP_NE p0, r{}, 0", value.reg));
        self.release(value);
        self.instr(&format!("JMP_IF_ANY p0, {label}"));
        Ok(())
    }

    fn switch_label(&self, id: usize) -> Option<String> {
        self.switch_labels
            .iter()
            .rev()
            .find_map(|labels| labels.iter().find(|(candidate, _)| *candidate == id))
            .map(|(_, label)| label.clone())
    }

    fn expr(&mut self, expr: &TypedExpr) -> Result<Value, Diagnostic> {
        match &expr.kind {
            TypedExprKind::Literal(value) => {
                let reg = self.alloc_reg(expr.span)?;
                self.instr(&format!("MOV r{reg}, {value}"));
                Ok(Value { reg, owned: true })
            }
            TypedExprKind::StringAddress(address) => {
                let reg = self.alloc_reg(expr.span)?;
                self.instr(&format!("MOV r{reg}, {address}"));
                Ok(Value { reg, owned: true })
            }
            TypedExprKind::LValue(lvalue) => {
                if expr.ty.is_array() || expr.ty.is_struct() {
                    self.lvalue_address(lvalue, expr.span)
                } else {
                    self.load_lvalue(lvalue, expr.span)
                }
            }
            TypedExprKind::AddressOf(lvalue) => self.lvalue_address(lvalue, expr.span),
            TypedExprKind::Unary(op, operand) => self.unary(*op, operand, expr),
            TypedExprKind::Binary {
                op,
                left,
                right,
                operand_type,
            } => self.binary(*op, left, right, *operand_type, expr),
            TypedExprKind::PointerAdd {
                pointer,
                index,
                scale,
                subtract,
            } => {
                let pointer = self.expr(pointer)?;
                let index = self.expr(index)?;
                let scaled = if *scale == 1 {
                    index
                } else {
                    let out = self.alloc_reg(expr.span)?;
                    self.instr(&format!("MUL r{out}, r{}, {scale}", index.reg));
                    self.release(index);
                    Value {
                        reg: out,
                        owned: true,
                    }
                };
                let out = self.alloc_reg(expr.span)?;
                let mnemonic = if *subtract { "SUB" } else { "ADD" };
                self.instr(&format!(
                    "{mnemonic} r{out}, r{}, r{}",
                    pointer.reg, scaled.reg
                ));
                self.release(pointer);
                self.release(scaled);
                Ok(Value {
                    reg: out,
                    owned: true,
                })
            }
            TypedExprKind::PointerDiff { left, right, scale } => {
                let left = self.expr(left)?;
                let right = self.expr(right)?;
                let delta = self.alloc_reg(expr.span)?;
                self.instr(&format!("SUB r{delta}, r{}, r{}", left.reg, right.reg));
                self.release(left);
                self.release(right);
                if *scale == 1 {
                    Ok(Value {
                        reg: delta,
                        owned: true,
                    })
                } else {
                    let divisor = self.alloc_reg(expr.span)?;
                    self.instr(&format!("MOV r{divisor}, {scale}"));
                    let out = self.signed_div_mod(BinaryOp::Div, delta, divisor, expr.span)?;
                    self.free_reg(divisor);
                    self.free_reg(delta);
                    Ok(Value {
                        reg: out,
                        owned: true,
                    })
                }
            }
            TypedExprKind::Assign {
                target,
                op,
                right,
                operation_type,
                scale,
            } => self.assignment(target, *op, right, *operation_type, *scale, expr),
            TypedExprKind::Call { function, args } => {
                self.call(*function, args, expr.ty, expr.span)
            }
            TypedExprKind::IncDec {
                target,
                increment,
                postfix,
                scale,
            } => {
                let current = self.load_lvalue(target, expr.span)?;
                if *postfix {
                    let old = self.alloc_reg(expr.span)?;
                    self.instr(&format!("MOV r{old}, r{}", current.reg));
                    let mnemonic = if *increment { "ADD" } else { "SUB" };
                    let updated = self.alloc_reg(expr.span)?;
                    self.instr(&format!("{mnemonic} r{updated}, r{}, {scale}", current.reg));
                    self.store_lvalue(target, updated, expr.span)?;
                    self.free_reg(updated);
                    self.release(current);
                    Ok(Value {
                        reg: old,
                        owned: true,
                    })
                } else {
                    let mnemonic = if *increment { "ADD" } else { "SUB" };
                    let updated = self.alloc_reg(expr.span)?;
                    self.instr(&format!("{mnemonic} r{updated}, r{}, {scale}", current.reg));
                    self.store_lvalue(target, updated, expr.span)?;
                    self.release(current);
                    Ok(Value {
                        reg: updated,
                        owned: true,
                    })
                }
            }
        }
    }

    fn call(
        &mut self,
        function: FunctionId,
        args: &[TypedExpr],
        return_type: Type,
        span: Span,
    ) -> Result<Value, Diagnostic> {
        let mut values = Vec::new();
        for arg in args {
            values.push(self.expr(arg)?);
        }

        let saved: Vec<u8> = self
            .used
            .iter()
            .enumerate()
            .filter_map(|(reg, used)| used.then_some(reg as u8))
            .collect();
        let return_slot = (return_type != Type::VOID).then_some(saved.len());
        let frame_slots = saved.len() + usize::from(return_slot.is_some());
        let frame_words = frame_slots * 32;
        if frame_words != 0 {
            self.instr(&format!(
                "S_ADD_I {STACK_POINTER}, {STACK_POINTER}, -{frame_words}"
            ));
        }
        for (slot, &reg) in saved.iter().enumerate() {
            self.stack_address(slot);
            self.instr(&format!("STORE r{STACK_ADDR_REG}, r{reg}"));
        }
        for (arg_reg, value) in values.iter().enumerate() {
            let Some(slot) = saved.iter().position(|&reg| reg == value.reg) else {
                return Err(Diagnostic::new(
                    span,
                    "internal error: argument register was not saved",
                ));
            };
            self.stack_address(slot);
            self.instr(&format!("LOAD r{arg_reg}, r{STACK_ADDR_REG}"));
        }
        let target = self.function_labels[function].clone();
        self.instr(&format!("CALL {target}"));
        if let Some(slot) = return_slot {
            self.stack_address(slot);
            self.instr(&format!("STORE r{STACK_ADDR_REG}, r0"));
        }
        for (slot, &reg) in saved.iter().enumerate() {
            self.stack_address(slot);
            self.instr(&format!("LOAD r{reg}, r{STACK_ADDR_REG}"));
        }
        for value in values {
            self.release(value);
        }

        let result = if let Some(slot) = return_slot {
            let out = self.alloc_reg(span)?;
            self.stack_address(slot);
            self.instr(&format!("LOAD r{out}, r{STACK_ADDR_REG}"));
            Value {
                reg: out,
                owned: true,
            }
        } else {
            Value {
                reg: 0,
                owned: false,
            }
        };
        if frame_words != 0 {
            self.instr(&format!(
                "S_ADD_I {STACK_POINTER}, {STACK_POINTER}, {frame_words}"
            ));
        }
        Ok(result)
    }

    fn stack_address(&mut self, slot: usize) {
        self.instr(&format!("S_BCAST r{STACK_ADDR_REG}, {STACK_POINTER}"));
        let offset = slot * 32;
        if offset != 0 {
            self.instr(&format!(
                "ADD r{STACK_ADDR_REG}, r{STACK_ADDR_REG}, {offset}"
            ));
        }
        self.instr(&format!(
            "ADD r{STACK_ADDR_REG}, r{STACK_ADDR_REG}, r{LANE_REG}"
        ));
    }

    fn unary(
        &mut self,
        op: UnaryOp,
        operand: &TypedExpr,
        expr: &TypedExpr,
    ) -> Result<Value, Diagnostic> {
        let value = self.expr(operand)?;
        match op {
            UnaryOp::Plus => Ok(value),
            UnaryOp::Minus | UnaryOp::BitNot => {
                let out = self.alloc_reg(expr.span)?;
                let mnemonic = if op == UnaryOp::Minus { "NEG" } else { "NOT" };
                self.instr(&format!("{mnemonic} r{out}, r{}", value.reg));
                self.release(value);
                Ok(Value {
                    reg: out,
                    owned: true,
                })
            }
            UnaryOp::LogicalNot => {
                let out = self.materialize_compare("CMP_EQ", value.reg, None, 0, expr.span)?;
                self.release(value);
                Ok(Value {
                    reg: out,
                    owned: true,
                })
            }
            _ => unreachable!("increment/decrement is represented separately by semantic analysis"),
        }
    }

    fn binary(
        &mut self,
        op: BinaryOp,
        left_expr: &TypedExpr,
        right_expr: &TypedExpr,
        operand_type: Type,
        expr: &TypedExpr,
    ) -> Result<Value, Diagnostic> {
        if op == BinaryOp::Comma {
            let left = self.expr(left_expr)?;
            self.release(left);
            return self.expr(right_expr);
        }
        if matches!(op, BinaryOp::LogicalAnd | BinaryOp::LogicalOr) {
            return self.logical(op, left_expr, right_expr, expr.span);
        }
        let left = self.expr(left_expr)?;
        let right = self.expr(right_expr)?;
        let out = self.emit_binary(op, left.reg, right.reg, operand_type, expr.span)?;
        self.release(left);
        self.release(right);
        Ok(Value {
            reg: out,
            owned: true,
        })
    }

    fn logical(
        &mut self,
        op: BinaryOp,
        left_expr: &TypedExpr,
        right_expr: &TypedExpr,
        span: Span,
    ) -> Result<Value, Diagnostic> {
        let out = self.alloc_reg(span)?;
        let end = self.label("logical_end");
        let left = self.expr(left_expr)?;
        self.instr(&format!("CMP_NE p0, r{}, 0", left.reg));
        self.release(left);
        match op {
            BinaryOp::LogicalAnd => {
                self.instr(&format!("MOV r{out}, 0"));
                self.instr("NOTMASK p1, p0");
                self.instr(&format!("JMP_IF_ANY p1, {end}"));
                let right = self.expr(right_expr)?;
                self.instr(&format!("CMP_NE p0, r{}, 0", right.reg));
                self.release(right);
                self.instr(&format!("@p0 MOV r{out}, 1"));
            }
            BinaryOp::LogicalOr => {
                self.instr(&format!("MOV r{out}, 1"));
                self.instr(&format!("JMP_IF_ANY p0, {end}"));
                let right = self.expr(right_expr)?;
                self.instr(&format!("CMP_EQ p0, r{}, 0", right.reg));
                self.release(right);
                self.instr(&format!("@p0 MOV r{out}, 0"));
            }
            _ => unreachable!(),
        }
        self.line(&format!("{end}:"));
        Ok(Value {
            reg: out,
            owned: true,
        })
    }

    fn assignment(
        &mut self,
        target: &LValue,
        op: AssignOp,
        right_expr: &TypedExpr,
        operation_type: Type,
        scale: usize,
        expr: &TypedExpr,
    ) -> Result<Value, Diagnostic> {
        let right = self.expr(right_expr)?;
        if op == AssignOp::Assign {
            self.store_lvalue(target, right.reg, expr.span)?;
            Ok(right)
        } else {
            let current = self.load_lvalue(target, expr.span)?;
            let right = if scale == 1 {
                right
            } else {
                let scaled = self.alloc_reg(expr.span)?;
                self.instr(&format!("MUL r{scaled}, r{}, {scale}", right.reg));
                self.release(right);
                Value {
                    reg: scaled,
                    owned: true,
                }
            };
            let binary = assignment_binary(op);
            let out =
                self.emit_binary(binary, current.reg, right.reg, operation_type, expr.span)?;
            self.release(current);
            self.release(right);
            self.store_lvalue(target, out, expr.span)?;
            Ok(Value {
                reg: out,
                owned: true,
            })
        }
    }

    fn emit_binary(
        &mut self,
        op: BinaryOp,
        left: u8,
        right: u8,
        operand_type: Type,
        span: Span,
    ) -> Result<u8, Diagnostic> {
        use BinaryOp::*;
        match op {
            Add | Sub | Mul | BitAnd | BitOr | BitXor | Shl => {
                let out = self.alloc_reg(span)?;
                let mnemonic = match op {
                    Add => "ADD",
                    Sub => "SUB",
                    Mul => "MUL",
                    BitAnd => "AND",
                    BitOr => "OR",
                    BitXor => "XOR",
                    Shl => "SHL",
                    _ => unreachable!(),
                };
                self.instr(&format!("{mnemonic} r{out}, r{left}, r{right}"));
                Ok(out)
            }
            Div | Mod if operand_type == Type::I32 => self.signed_div_mod(op, left, right, span),
            Div | Mod => {
                let out = self.alloc_reg(span)?;
                let mnemonic = if op == Div { "DIV" } else { "MOD" };
                self.instr(&format!("{mnemonic} r{out}, r{left}, r{right}"));
                Ok(out)
            }
            Shr if operand_type == Type::I32 => self.arithmetic_shift_right(left, right, span),
            Shr => {
                let out = self.alloc_reg(span)?;
                self.instr(&format!("SHR r{out}, r{left}, r{right}"));
                Ok(out)
            }
            Eq | Ne => {
                let mnemonic = if op == Eq { "CMP_EQ" } else { "CMP_NE" };
                self.materialize_compare(mnemonic, left, Some(right), 0, span)
            }
            Lt | Le | Gt | Ge => self.relational(op, left, right, operand_type, span),
            LogicalAnd | LogicalOr | Comma => unreachable!(),
        }
    }

    fn signed_div_mod(
        &mut self,
        op: BinaryOp,
        left: u8,
        right: u8,
        span: Span,
    ) -> Result<u8, Diagnostic> {
        let out = self.alloc_reg(span)?;
        let temp = self.alloc_reg(span)?;
        self.instr(&format!("ABS r{out}, r{left}"));
        self.instr(&format!("ABS r{temp}, r{right}"));
        let mnemonic = if op == BinaryOp::Div { "DIV" } else { "MOD" };
        self.instr(&format!("{mnemonic} r{out}, r{out}, r{temp}"));
        if op == BinaryOp::Div {
            self.instr(&format!("XOR r{temp}, r{left}, r{right}"));
        } else {
            self.instr(&format!("MOV r{temp}, r{left}"));
        }
        self.instr(&format!("CMP_GE p0, r{temp}, {SIGN_BIT}"));
        self.instr(&format!("@p0 NEG r{out}, r{out}"));
        self.free_reg(temp);
        Ok(out)
    }

    fn arithmetic_shift_right(
        &mut self,
        left: u8,
        right: u8,
        span: Span,
    ) -> Result<u8, Diagnostic> {
        let out = self.alloc_reg(span)?;
        let fill = self.alloc_reg(span)?;
        let neg_shift = self.alloc_reg(span)?;
        self.instr(&format!("SHR r{out}, r{left}, r{right}"));
        self.instr(&format!("SHR r{fill}, r{left}, 31"));
        self.instr(&format!("NEG r{fill}, r{fill}"));
        self.instr(&format!("NEG r{neg_shift}, r{right}"));
        self.instr(&format!("SHL r{fill}, r{fill}, r{neg_shift}"));
        self.instr(&format!("CMP_EQ p0, r{right}, 0"));
        self.instr(&format!("@!p0 OR r{out}, r{out}, r{fill}"));
        self.free_reg(neg_shift);
        self.free_reg(fill);
        Ok(out)
    }

    fn relational(
        &mut self,
        op: BinaryOp,
        left: u8,
        right: u8,
        ty: Type,
        span: Span,
    ) -> Result<u8, Diagnostic> {
        let mnemonic = match op {
            BinaryOp::Lt => "CMP_LT",
            BinaryOp::Le => "CMP_LE",
            BinaryOp::Gt => "CMP_GT",
            BinaryOp::Ge => "CMP_GE",
            _ => unreachable!(),
        };
        if ty != Type::I32 {
            return self.materialize_compare(mnemonic, left, Some(right), 0, span);
        }
        let biased_left = self.alloc_reg(span)?;
        let biased_right = self.alloc_reg(span)?;
        self.instr(&format!("XOR r{biased_left}, r{left}, {SIGN_BIT}"));
        self.instr(&format!("XOR r{biased_right}, r{right}, {SIGN_BIT}"));
        let out = self.materialize_compare(mnemonic, biased_left, Some(biased_right), 0, span)?;
        self.free_reg(biased_right);
        self.free_reg(biased_left);
        Ok(out)
    }

    fn materialize_compare(
        &mut self,
        mnemonic: &str,
        left: u8,
        right: Option<u8>,
        immediate: u32,
        span: Span,
    ) -> Result<u8, Diagnostic> {
        match right {
            Some(right) => self.instr(&format!("{mnemonic} p0, r{left}, r{right}")),
            None => self.instr(&format!("{mnemonic} p0, r{left}, {immediate}")),
        }
        let out = self.alloc_reg(span)?;
        self.instr(&format!("MOV r{out}, 0"));
        self.instr(&format!("@p0 MOV r{out}, 1"));
        Ok(out)
    }

    fn local_reg(&self, local: LocalId, span: Span) -> Result<u8, Diagnostic> {
        self.local_regs[local]
            .ok_or_else(|| Diagnostic::new(span, "internal error: local has no allocated register"))
    }

    fn emit_return(&mut self) {
        if self.current_frame_words != 0 {
            self.instr(&format!(
                "S_ADD_I {STACK_POINTER}, {STACK_POINTER}, {}",
                self.current_frame_words * 32
            ));
        }
        if self.current_function == Some(self.main_function) {
            self.instr("HALT");
        } else {
            self.instr("RET");
        }
    }

    fn local_address(&mut self, local: LocalId, span: Span) -> Result<Value, Diagnostic> {
        self.local_address_offset(local, 0, span)
    }

    fn local_address_offset(
        &mut self,
        local: LocalId,
        extra: usize,
        span: Span,
    ) -> Result<Value, Diagnostic> {
        let offset = self.locals[local]
            .frame_offset
            .ok_or_else(|| Diagnostic::new(span, "cannot take address of register-only local"))?
            + extra;
        let out = self.alloc_reg(span)?;
        self.instr(&format!("S_BCAST r{out}, {STACK_POINTER}"));
        if self.current_frame_words != 0 {
            self.instr(&format!(
                "MUL r{STACK_ADDR_REG}, r{LANE_REG}, {}",
                self.current_frame_words
            ));
            self.instr(&format!("ADD r{out}, r{out}, r{STACK_ADDR_REG}"));
        }
        if offset != 0 {
            self.instr(&format!("ADD r{out}, r{out}, {offset}"));
        }
        Ok(Value {
            reg: out,
            owned: true,
        })
    }

    fn lvalue_address(&mut self, lvalue: &LValue, span: Span) -> Result<Value, Diagnostic> {
        match lvalue {
            LValue::Local(local) => self.local_address(*local, span),
            LValue::Global(global) => {
                let out = self.alloc_reg(span)?;
                self.instr(&format!("MOV r{out}, {}", self.globals[*global].address));
                Ok(Value {
                    reg: out,
                    owned: true,
                })
            }
            LValue::Deref(pointer) => self.expr(pointer),
            LValue::Index { base, index, scale } => {
                let base = self.expr(base)?;
                let index = self.expr(index)?;
                let scaled = if *scale == 1 {
                    index
                } else {
                    let out = self.alloc_reg(span)?;
                    self.instr(&format!("MUL r{out}, r{}, {scale}", index.reg));
                    self.release(index);
                    Value {
                        reg: out,
                        owned: true,
                    }
                };
                let out = self.alloc_reg(span)?;
                self.instr(&format!("ADD r{out}, r{}, r{}", base.reg, scaled.reg));
                self.release(base);
                self.release(scaled);
                Ok(Value {
                    reg: out,
                    owned: true,
                })
            }
            LValue::Member { base, offset } => {
                let address = self.lvalue_address(base, span)?;
                if *offset == 0 {
                    return Ok(address);
                }
                let out = self.alloc_reg(span)?;
                self.instr(&format!("ADD r{out}, r{}, {offset}", address.reg));
                self.release(address);
                Ok(Value {
                    reg: out,
                    owned: true,
                })
            }
        }
    }

    fn load_lvalue(&mut self, lvalue: &LValue, span: Span) -> Result<Value, Diagnostic> {
        if let LValue::Local(local) = lvalue {
            if self.locals[*local].frame_offset.is_none() {
                return Ok(Value {
                    reg: self.local_reg(*local, span)?,
                    owned: false,
                });
            }
        }
        let address = self.lvalue_address(lvalue, span)?;
        let out = self.alloc_reg(span)?;
        self.instr(&format!("LOAD r{out}, r{}", address.reg));
        self.release(address);
        Ok(Value {
            reg: out,
            owned: true,
        })
    }

    fn store_lvalue(&mut self, lvalue: &LValue, source: u8, span: Span) -> Result<(), Diagnostic> {
        if let LValue::Local(local) = lvalue {
            if self.locals[*local].frame_offset.is_none() {
                let target = self.local_reg(*local, span)?;
                if target != source {
                    self.instr(&format!("MOV r{target}, r{source}"));
                }
                return Ok(());
            }
        }
        let address = self.lvalue_address(lvalue, span)?;
        self.instr(&format!("STORE r{}, r{source}", address.reg));
        self.release(address);
        Ok(())
    }

    fn alloc_reg(&mut self, span: Span) -> Result<u8, Diagnostic> {
        let Some(reg) = self.used.iter().position(|used| !*used) else {
            return Err(Diagnostic::new(
                span,
                "vector register exhaustion (simplify the expression)",
            ));
        };
        self.used[reg] = true;
        Ok(reg as u8)
    }

    fn free_reg(&mut self, reg: u8) {
        debug_assert!((reg as usize) < ALLOCATABLE_REGS && self.used[reg as usize]);
        self.used[reg as usize] = false;
    }

    fn release(&mut self, value: Value) {
        if value.owned {
            self.free_reg(value.reg);
        }
    }

    fn label(&mut self, stem: &str) -> String {
        let label = format!("__warpc_{stem}_{}", self.next_label);
        self.next_label += 1;
        label
    }

    fn line(&mut self, text: &str) {
        self.assembly.push_str(text);
        self.assembly.push('\n');
    }

    fn instr(&mut self, text: &str) {
        self.assembly.push_str("    ");
        self.line(text);
    }
}

fn assignment_binary(op: AssignOp) -> BinaryOp {
    match op {
        AssignOp::Add => BinaryOp::Add,
        AssignOp::Sub => BinaryOp::Sub,
        AssignOp::Mul => BinaryOp::Mul,
        AssignOp::Div => BinaryOp::Div,
        AssignOp::Mod => BinaryOp::Mod,
        AssignOp::Shl => BinaryOp::Shl,
        AssignOp::Shr => BinaryOp::Shr,
        AssignOp::BitAnd => BinaryOp::BitAnd,
        AssignOp::BitXor => BinaryOp::BitXor,
        AssignOp::BitOr => BinaryOp::BitOr,
        AssignOp::Assign => unreachable!(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{lexer, parser, sema};

    fn assembly(source: &str) -> String {
        let tokens = lexer::lex(source).unwrap();
        let ast = parser::parse(&tokens).unwrap();
        let typed = sema::analyze(ast).unwrap();
        generate(&typed).unwrap()
    }

    #[test]
    fn signed_operations_use_explicit_lowering() {
        let text = assembly(
            "int main(void) { int a = -21; int b = 4; return a / b + (a >> b) + (a < b); }",
        );
        assert!(text.contains("ABS"));
        assert!(text.contains("@p0 NEG"));
        assert!(text.contains("@!p0 OR"));
        assert!(text.contains("2147483648"));
    }

    #[test]
    fn logical_and_is_short_circuit_control_flow() {
        let text = assembly("int main(void) { int x = 0; return x && ++x; }");
        assert!(text.contains("JMP_IF_ANY"));
        assert!(text.contains("logical_end"));
    }

    #[test]
    fn structured_control_emits_explicit_targets() {
        let text = assembly(
            "int main(void) { int x = 0; while (x < 3) { ++x; if (x == 2) continue; } do { --x; } while (x); for (int i = 0; i < 2; ++i) { if (i) continue; x += i; } return x; }",
        );
        assert!(text.contains("while_condition"));
        assert!(text.contains("do_condition"));
        assert!(text.contains("for_step"));
        assert!(text.contains("JMP __warpc_for_step"));
    }

    #[test]
    fn switch_emits_dispatch_and_case_labels() {
        let text = assembly(
            "int main(void) { int x = 2; switch (x) { case 1: x = 3; case 1 + 1: x = 42; break; default: x = 0; } return x; }",
        );
        assert!(text.contains("CMP_EQ p0"));
        assert!(text.contains("switch_case"));
        assert!(text.contains("switch_end"));
    }

    #[test]
    fn calls_use_the_lane_private_stack_abi() {
        let text = assembly(
            "int add(int, int); int main(void) { int keep = 20; return add(keep, 22); } int add(int a, int b) { return a + b; }",
        );
        assert!(text.contains("LANEID r13"));
        assert!(text.contains("S_MOV_I s7, 16384"));
        assert!(text.contains("S_ADD_I s7, s7, -"));
        assert!(text.contains("STORE r14"));
        assert!(text.contains("CALL __warpc_fn_add"));
        assert!(text.contains("__warpc_fn_add:"));
        assert!(text.contains("RET"));
    }

    #[test]
    fn memory_objects_use_word_addressed_load_store() {
        let text = assembly(
            "struct P { int x; char s[3]; }; int main(void) { struct P p; int n=4; int *q=&n; p.s[1]='A'; return *q + p.s[1] + sizeof(p); }",
        );
        assert!(text.contains("MUL r14, r13"));
        assert!(text.contains("LOAD"));
        assert!(text.contains("STORE"));
        assert!(!text.contains("SHL r14, r13, 2"));
    }
}
